name: Day3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Touch input
      run: touch crates/day3/src/input.txt
    - name: Check
      run: cargo check -p day3
    - name: Run tests
      run: cargo test -p day3
