name: Previous Days

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  previous:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Touch input
      run: touch crates/day1/src/input.txt &&
           touch crates/day2/src/input.txt &&
           touch crates/day3/src/input.txt &&
           touch crates/day4/src/input.txt &&
           touch crates/day5/src/input.txt &&
           touch crates/day6/src/input.txt &&
           touch crates/day7/src/input.txt &&
           touch crates/day8/src/input.txt &&
           touch crates/day9/src/input.txt &&
           touch crates/day10/src/input.txt
    - name: Check
      run: cargo check --workspace --exclude day11 --exclude day12
    - name: Run tests
      run: cargo test --workspace --exclude day11 --exclude day12
