name: Previous Days

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  previous:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Touch input
      run: touch crates/day1/src/input.txt
      run: touch crates/day2/src/input.txt
      run: touch crates/day3/src/input.txt
      run: touch crates/day4/src/input.txt
      run: touch crates/day5/src/input.txt
    - name: Check
      run: cargo check --workspace --exclude day6
    - name: Run tests
      run: cargo test -- --skip -p day6
